# Generated by Django 4.1.3 on 2022-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='com_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
