# Generated by Django 4.1.3 on 2022-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_competition_com_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='com_winner',
            field=models.CharField(default='no winners', max_length=200),
        ),
    ]
